{% set name = "mdutils" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdutils-{{ version }}.tar.gz
  sha256: 647f3cf00df39fee6c57fa6738dc1160fce1788276b5530c87d43a70cdefdaf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - mdutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/didix21/mdutils
  summary: Useful package for creating Markdown files while executing python code.
  dev_url: https://github.com/didix21/mdutils
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
